# NixOS-level module: runs eigenhome activation scripts after files are linked.
#
# Creates an eigenhome-user-activation@<user>.service template that:
#   1. Runs after eigenhome-activate@<user>.service (files are linked)
#   2. Runs before eigenhome-copy@<user>.service (manifest is committed)
#   3. Triggers systemctl --user daemon-reload (picks up new/changed units)
#   4. Executes the activation script if it exists
#   5. Diffs old vs new user service units and restarts/stops/starts as needed
#
# Dependency chain:
#   eigenhome.target → eigenhome-activate@alice → eigenhome-user-activation@alice → eigenhome-copy@alice
{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (builtins) attrValues concatLists;
  inherit
    (lib)
    attrNames
    concatStringsSep
    filter
    filterAttrs
    mapAttrs
    mapAttrsToList
    mkIf
    optionalString
    ;

  cfg = config.eigenhome;
  enabledUsers = filterAttrs (_: u: u.enable) cfg.users;
  hasUsers = enabledUsers != {};
  hasLinker = cfg.linker != null;

  allUserFiles = user:
    concatLists (map attrValues [
      user.files
      user.xdg.cache.files
      user.xdg.config.files
      user.xdg.data.files
      user.xdg.state.files
    ]);

  userOnChangeScripts = mapAttrs (username: user: let
    files = filter (f: f.enable && f.onChange != "" && f.source != null) (allUserFiles user);
  in
    if files == []
    then null
    else
      pkgs.writeShellScript "eigenhome-onchange-${username}" ''
        _manifest="/var/lib/eigenhome/manifest-$(id -un).json"
        ${concatStringsSep "\n" (map (f: ''
          # onChange: ${f.target}
          _old_src="$(${pkgs.jq}/bin/jq -r --arg t ${lib.escapeShellArg f.target} \
            '.files[] | select(.target == $t) | .source // empty' \
            "$_manifest" 2>/dev/null || true)"
          if [ -z "$_old_src" ] || [ "$_old_src" != ${lib.escapeShellArg (toString f.source)} ]; then
            ${f.onChange}
          fi
        '') files)}
      '')
    enabledUsers;

  onChangeDir = let
    scripts = filterAttrs (_: s: s != null) userOnChangeScripts;
  in
    if scripts == {}
    then null
    else
      pkgs.linkFarm "eigenhome-onchange" (
        mapAttrsToList (name: path: {inherit name path;}) scripts
      );
in {
  config = mkIf (hasUsers && hasLinker) {
    systemd.services."eigenhome-user-activation@" = {
      description = "Run user activation scripts for %i";
      serviceConfig = {
        User = "%i";
        Type = "oneshot";
      };
      after = ["eigenhome-activate@%i.service"];
      requires = ["eigenhome-activate@%i.service"];
      before = ["eigenhome-copy@%i.service"];
      script = ''
        export XDG_RUNTIME_DIR="/run/user/$(id -u)"

        # Reload systemd user daemon to pick up new/changed unit files.
        systemctl --user daemon-reload || true

        # Run activation script if generated by eigenhome.
        activate="$HOME/.local/share/eigenhome/activate"
        if [ -x "$activate" ]; then
          "$activate"
        fi

        ${optionalString (onChangeDir != null) ''
          # Run onChange hooks for deployed files.
          _onchange="${onChangeDir}/$(id -un)"
          if [ -x "$_onchange" ]; then
            "$_onchange"
          fi
        ''}

        # Manage user service lifecycle via sd-switch.
        # sd-switch diffs old vs new unit directories and handles start/stop/restart/reload,
        # including X-Restart-Triggers, X-Reload-Triggers, X-SwitchMethod, and RefuseManualStart.
        _new_units="$(readlink "$HOME/.config/systemd/user" 2>/dev/null || true)"
        _old_manifest="/var/lib/eigenhome/manifest-$(id -un).json"

        if [ -n "$_new_units" ] && [ -d "$_new_units" ]; then
          _old_units=""
          if [ -f "$_old_manifest" ]; then
            _maybe_old="$(${pkgs.jq}/bin/jq -r \
              '.files[] | select(.target | endswith("/.config/systemd/user")) | .source' \
              "$_old_manifest" 2>/dev/null || true)"
            if [ -n "$_maybe_old" ] && [ -d "$_maybe_old" ]; then
              _old_units="$_maybe_old"
            fi
          fi

          ${pkgs.sd-switch}/bin/sd-switch \
            ''${_old_units:+--old-units "$_old_units"} \
            --new-units "$_new_units" || true
        fi
      '';
    };

    # Extend eigenhome.target to include our activation service for each user.
    systemd.targets.eigenhome.requires =
      map (user: "eigenhome-user-activation@${user}.service") (attrNames enabledUsers);
  };
}
