# NixOS-level module: runs eigenhome activation scripts after files are linked.
#
# Creates an eigenhome-user-activation@<user>.service template that:
#   1. Runs after eigenhome-activate@<user>.service (files are linked)
#   2. Runs before eigenhome-copy@<user>.service (manifest is committed)
#   3. Triggers systemctl --user daemon-reload (picks up new/changed units)
#   4. Executes the activation script if it exists
#   5. Diffs old vs new user service units and restarts/stops/starts as needed
#
# Dependency chain:
#   eigenhome.target → eigenhome-activate@alice → eigenhome-user-activation@alice → eigenhome-copy@alice
{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (builtins) attrValues concatLists;
  inherit
    (lib)
    attrNames
    concatStringsSep
    filter
    filterAttrs
    mapAttrs
    mapAttrsToList
    mkIf
    optionalString
    ;

  cfg = config.eigenhome;
  enabledUsers = filterAttrs (_: u: u.enable) cfg.users;
  hasUsers = enabledUsers != {};
  hasLinker = cfg.linker != null;

  allUserFiles = user:
    concatLists (map attrValues [
      user.files
      user.xdg.cache.files
      user.xdg.config.files
      user.xdg.data.files
      user.xdg.state.files
    ]);

  userOnChangeScripts = mapAttrs (username: user: let
    files = filter (f: f.enable && f.onChange != "" && f.source != null) (allUserFiles user);
  in
    if files == []
    then null
    else
      pkgs.writeShellScript "eigenhome-onchange-${username}" ''
        _manifest="/var/lib/eigenhome/manifest-$(id -un).json"
        ${concatStringsSep "\n" (map (f: ''
          # onChange: ${f.target}
          _old_src="$(${pkgs.jq}/bin/jq -r --arg t ${lib.escapeShellArg f.target} \
            '.files[] | select(.target == $t) | .source // empty' \
            "$_manifest" 2>/dev/null || true)"
          if [ -z "$_old_src" ] || [ "$_old_src" != ${lib.escapeShellArg (toString f.source)} ]; then
            ${f.onChange}
          fi
        '') files)}
      '')
    enabledUsers;

  onChangeDir = let
    scripts = filterAttrs (_: s: s != null) userOnChangeScripts;
  in
    if scripts == {}
    then null
    else
      pkgs.linkFarm "eigenhome-onchange" (
        mapAttrsToList (name: path: {inherit name path;}) scripts
      );
in {
  config = mkIf (hasUsers && hasLinker) {
    systemd.services."eigenhome-user-activation@" = {
      description = "Run user activation scripts for %i";
      serviceConfig = {
        User = "%i";
        Type = "oneshot";
      };
      after = ["eigenhome-activate@%i.service"];
      requires = ["eigenhome-activate@%i.service"];
      before = ["eigenhome-copy@%i.service"];
      script = ''
        export XDG_RUNTIME_DIR="/run/user/$(id -u)"

        # Reload systemd user daemon to pick up new/changed unit files.
        systemctl --user daemon-reload || true

        # Run activation script if generated by eigenhome.
        activate="$HOME/.local/share/eigenhome/activate"
        if [ -x "$activate" ]; then
          "$activate"
        fi

        ${optionalString (onChangeDir != null) ''
          # Run onChange hooks for deployed files.
          _onchange="${onChangeDir}/$(id -un)"
          if [ -x "$_onchange" ]; then
            "$_onchange"
          fi
        ''}

        # Diff old vs new user service units and restart/stop/start as needed.
        # New units dir: resolved from the symlink the linker already updated.
        # Old units dir: extracted from the previous manifest (not yet overwritten).
        _new_units="$(readlink "$HOME/.config/systemd/user" 2>/dev/null || true)"
        _old_manifest="/var/lib/eigenhome/manifest-$(id -un).json"

        if [ -n "$_new_units" ] && [ -d "$_new_units" ]; then
          _old_units=""
          if [ -f "$_old_manifest" ]; then
            _old_units="$(${pkgs.jq}/bin/jq -r \
              '.files[] | select(.target | endswith("/.config/systemd/user")) | .source' \
              "$_old_manifest" 2>/dev/null || true)"
          fi

          if [ -z "$_old_units" ] || [ ! -d "$_old_units" ]; then
            # First activation or no previous units: start all non-template services.
            for _f in "$_new_units"/*.service; do
              [ -f "$_f" ] || continue
              _unit="$(basename "$_f")"
              case "$_unit" in *@.service) continue ;; esac
              systemctl --user start "$_unit" 2>/dev/null || true
            done
          elif [ "$_old_units" != "$_new_units" ]; then
            # Units dir changed: diff services and act accordingly.
            {
              (cd "$_old_units" && ls *.service 2>/dev/null || true)
              (cd "$_new_units" && ls *.service 2>/dev/null || true)
            } | grep -v '@\.service$' | sort -u | while read -r _unit; do
              _old_file="$_old_units/$_unit"
              _new_file="$_new_units/$_unit"

              if [ ! -f "$_new_file" ]; then
                # Service removed: stop if running.
                systemctl --user stop "$_unit" 2>/dev/null || true
              elif [ ! -f "$_old_file" ]; then
                # Service added: start it.
                systemctl --user start "$_unit" 2>/dev/null || true
              elif ! cmp --quiet "$_old_file" "$_new_file" 2>/dev/null; then
                # Service changed: restart if currently active.
                if systemctl --user is-active --quiet "$_unit" 2>/dev/null; then
                  systemctl --user restart "$_unit" || true
                fi
              fi
            done
          fi
        fi
      '';
    };

    # Extend eigenhome.target to include our activation service for each user.
    systemd.targets.eigenhome.requires =
      map (user: "eigenhome-user-activation@${user}.service") (attrNames enabledUsers);
  };
}
